# Python para Análise de Dados - Numpy   

<p> Iremos aprender a trabalhar coma biblioteca Numpy.


# Acessando Dimensões no Array

In [9]:
# Importando o Numpy
import numpy as np

In [33]:
# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha,coluna
my_array = np.random.random([10,2])

In [34]:
my_array

array([[0.81169459, 0.66552335],
       [0.85665748, 0.10892457],
       [0.93889139, 0.4090067 ],
       [0.99697936, 0.87251789],
       [0.70323551, 0.01625542],
       [0.59785624, 0.91260142],
       [0.5520251 , 0.01707174],
       [0.70656489, 0.75574784],
       [0.41219574, 0.91331928],
       [0.44512641, 0.54718482]])

In [35]:
# Imprimindo o primeiro elemento (1 linha)
my_array[0]

array([0.81169459, 0.66552335])

In [13]:
# Imprimindo o primeiro elemento da coluna 0 (1 coluna)
my_array[0][0]

0.9619912167031434

In [14]:
# Primeiro elemento da coluna 1
my_array[0][1]

0.12632099561673693

In [15]:
# Segundo elemento da coluna 1
my_array[1][1]

0.4838623008227748

In [16]:
# Segundo elemento da coluna escrito com virgula.
# O primeiro valor especifica a linha e o segundo valor especifica a coluna.
my_array[1,1]

0.4838623008227748

In [39]:
my_array[:,1]

array([0.66552335, 0.10892457, 0.4090067 , 0.87251789, 0.01625542,
       0.91260142, 0.01707174, 0.75574784, 0.91331928, 0.54718482])

In [17]:
# Imprimindo até 3 valores da coluna 1
my_array[:3,1]

array([0.126321  , 0.4838623 , 0.48927279])

In [ ]:
my_array

In [18]:
# Imprime todas as linhas da coluna 2 * 10
my_array[:,1] * 10

array([1.26320996, 4.83862301, 4.89272793, 5.58951713, 2.18363854,
       7.57721788, 2.18724356, 0.90515813, 6.16923167, 7.00312191])

In [19]:
# Comparação retorna indices
my_array > 0.50

array([[ True, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True, False],
       [False,  True],
       [ True, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [20]:
# Acessando valores por índices
my_array[my_array > 0.50]

array([0.96199122, 0.60621872, 0.55895171, 0.87913199, 0.75772179,
       0.83810323, 0.5908678 , 0.61692317, 0.59878716, 0.70031219])

# Carregar Arrays NumPy a partir de arquivos de Texto

In [21]:
import numpy as np

In [26]:
# Lendo um arquivo do tipo .txt
dataset = np.loadtxt('dataset_array.txt', delimiter=',')
dataset

array([1., 2., 3., 4., 5., 6.])

In [23]:
dataset.shape

(6,)

In [24]:
dataset

array([1., 2., 3., 4., 5., 6.])

In [27]:
# carregando um arquivo dividido em 3 arrays
a, b, c = np.loadtxt('dataset_valores.txt', skiprows=1, unpack=True )

In [28]:
# Array a
a

array([0.4839, 0.1292, 0.1781, 0.7676, 0.5993])

In [29]:
# Array B
b

array([0.4536, 0.6875, 0.3049, 0.5801, 0.4357])

In [30]:
# Array C
c

array([0.3561, 0.6565, 0.8928, 0.2038, 0.741 ])

In [31]:
# Carrega o arquivo ignorando as 2 primeiras linhas e preenchendo os valores vazio por 0
# Obs: os valores string também são convertidos!!

dataset = np.genfromtxt('dataset_valores_vazio.txt', skip_header=2, filling_values=0)

In [32]:
# Imprimindo o dataset
dataset

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.    ],
       [0.1781, 0.3049, 0.8928],
       [0.    , 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])