# Python para Análise de Dados - Numpy   

<p> Iremos aprender a trabalhar coma biblioteca Numpy.


In [1]:
# Importando a biblioteca numpy
import numpy as np

In [2]:
# Criando um array de 1 dimensão
one_dim = np.array([1,2,3,4])

In [3]:
type(one_dim)

numpy.ndarray

In [4]:
# Imprimindo um array.
one_dim.ndim

1

In [5]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [6]:
# Imprimindo o array
two_dim.ndim

2

In [11]:
two_dim[0,2]

3

In [14]:
# Cria um array de números aleatórios.
# Um array de 5 linhas e duas dimensões.
# chamo a classe random e depois o método random
np.random.random((5,2))

array([[0.21710236, 0.2269235 ],
       [0.84828528, 0.76446476],
       [0.57952457, 0.2831761 ],
       [0.05563458, 0.46438735],
       [0.95754178, 0.71609959]])

In [13]:
# Cria um array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5.
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
# cria um array linear de 0 a 2 de no máximo 9 elementos.
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [16]:
# Cria um array de valores zero.
# Cria um array com 3 linhas e 4 dimensões.
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Numpy Arrays Vs Listas

- Arrays Numpy permitem fazermos operações em **arrays inteiros** de forma rápida.
- Listas não permitem operações em todos os elementos da lista.
- Para operações em todos os elementos é preciso interar sobre toda a lista.
- Listas em Python armazenam diferentes tipos de objetos
- Arrays Numpy considera todos os elementos de tipos distintos como strings


In [17]:
# Criando uma lista em Python.
lista = [1,2,3]

In [18]:
lista

[1, 2, 3]

In [19]:
# Multiplicar valores da lista por 2.
lista * 2

[1, 2, 3, 1, 2, 3]

In [20]:
# Transforme a variável lista em um array Numpy
lista = np.array(lista)

In [21]:
# Imprimindo o tipo do objeto.
type(lista)

numpy.ndarray

In [22]:
# Multiplicando cada elemento por 2.
lista * 2

array([2, 4, 6])

In [23]:
# Calcular IMC de pessoas.
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [24]:
# Faz o calculo usando as listas
pesos / altura ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [28]:
imcs = [peso / (altura ** 2) for peso, altura in zip(pesos, altura)]

for imc in imcs:
    print(f'IMC: {imc:.2f}')

IMC: 23.74
IMC: 28.03
IMC: 39.18
IMC: 26.30


In [30]:
# Loop para exibir os resultados com detalhes sobre a altura e o peso
for peso, altura, imc in zip(pesos, altura, imcs):
    print(f'A pessoa com a altura {altura}m e peso {peso}kg possui um IMC de {imc:.2f}')

A pessoa com a altura 1.68m e peso 67kg possui um IMC de 23.74
A pessoa com a altura 1.7m e peso 81kg possui um IMC de 28.03
A pessoa com a altura 1.75m e peso 120kg possui um IMC de 39.18
A pessoa com a altura 1.85m e peso 90kg possui um IMC de 26.30


In [25]:
# Transforme isso em arrays numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [26]:
# Imprime o calculo de cada valor
pesos / altura **2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [31]:
# Arrays Numpy armazena elementos como strins quando estes não são inteiros ou float
a = np.array([1,3,'Casa',True])

In [32]:
a

array(['1', '3', 'Casa', 'True'], dtype='<U21')

In [33]:
a * 2 

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

# Métodos e Atributos Úteis

In [ ]:
# Métodos disponíveis (digite o . pressione tab).
two_dim.

In [115]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# Retorna a forma do array no formato linhas e colunas.
two_dim.shape

(2, 3)

In [35]:
# Retorna a quantidade de dimensões.
two_dim.ndim

2

In [36]:
# Imprimindo o valor máximo do array.
two_dim.max()

6

In [37]:
# Imprimindo o valor mínimo.
two_dim.min()

1

In [38]:
# Imprimindo o valor médio.
two_dim.mean()

3.5

In [39]:
# Imprimindo o desvio padrão.
two_dim.std()

1.707825127659933

In [40]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
two_dim.dtype

dtype('int64')

In [42]:
two_dim.size

6

In [43]:
# mostra a quantidade
two_dim.itemsize

8

In [127]:
# Somando todos os elementos do array.
two_dim.sum()

21

#  Transformando Arrays

In [44]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
# Gera a Transposta da Matriz (Linha -> coluna)
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
# Transforma em uma matriz de uma linha.
# È muito comum em bibliotecas como scikit-learn e Keras
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [48]:
tree = np.random.random((5,3))

In [49]:
tree.shape

(5, 3)

In [51]:
tree

array([[0.35318989, 0.1294245 , 0.88853749],
       [0.19919192, 0.30577035, 0.77325528],
       [0.14478143, 0.8763035 , 0.33480044],
       [0.07382145, 0.62909458, 0.04196653],
       [0.3070307 , 0.15751811, 0.47381217]])

In [52]:
# Transforma em uma matriz com 3 linhas e 5 colunas
tree.reshape(3,5)

array([[0.35318989, 0.1294245 , 0.88853749, 0.19919192, 0.30577035],
       [0.77325528, 0.14478143, 0.8763035 , 0.33480044, 0.07382145],
       [0.62909458, 0.04196653, 0.3070307 , 0.15751811, 0.47381217]])

In [53]:
tree.reshape(-1)

array([0.35318989, 0.1294245 , 0.88853749, 0.19919192, 0.30577035,
       0.77325528, 0.14478143, 0.8763035 , 0.33480044, 0.07382145,
       0.62909458, 0.04196653, 0.3070307 , 0.15751811, 0.47381217])

In [54]:
t=tree.reshape(1,15)
t

array([[0.35318989, 0.1294245 , 0.88853749, 0.19919192, 0.30577035,
        0.77325528, 0.14478143, 0.8763035 , 0.33480044, 0.07382145,
        0.62909458, 0.04196653, 0.3070307 , 0.15751811, 0.47381217]])

In [55]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
# Adicionando elementos a um array.
two_dim = np.insert(two_dim,0,10)

In [57]:
# Transforma em um array de uma linha.
two_dim

array([10,  1,  2,  3,  4,  5,  6])

In [58]:
# Apagando o elemento da primeira posição do array.
two_dim = np.delete(two_dim,[0])

In [59]:
two_dim

array([1, 2, 3, 4, 5, 6])

In [60]:
# Gerando um arquivo .txt a partir de um array
np.savetxt("dataset_array.txt",two_dim, delimiter=',')